spring.application.name=auth-service

# Conexión Directa a tu Base de Datos en Google Cloud
spring.datasource.url=jdbc:postgresql://8.35.197.211:5432/alkewallet_auth_db
spring.datasource.username=postgres
spring.datasource.password=i%K3Ru4%24<_^]*?
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' para que Spring cree las tablas automáticamente en Google Cloud en la primera corrida
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto del servicio
server.port=${PORT:8080}
spring.main.allow-circular-references=true

# Seguridad JWT (Mantén tu clave larga de desarrollo)
jwt.secret=TuClaveSecretaSuperSeguraYExtremadamenteLargaParaAlkeWalletCyberNeon2026
jwt.expiration=86400000