# Nombre de la aplicación
spring.application.name=auth-service

spring.datasource.url=${DB_URL:jdbc:postgresql:///alkewallet_auth_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Alkewallet_2026}
#valores para timeout y lifetime
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.keepalive-time=30000

# Configuración del starter de Google Cloud SQL
spring.cloud.gcp.sql.instance-connection-name=verdant-doodad-385514:us-central1:alkewallet-postgres1
spring.cloud.gcp.sql.database-name=alkewallet_auth_db

# --- CONFIGURACIÓN DE HIBERNATE / JPA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURACIÓN DEL SERVIDOR ---
server.port=${PORT:8080}
spring.main.allow-circular-references=true

# --- SEGURIDAD Y CONFIGURACIONES APP ---
jwt.secret=TuClaveSecretaSuperSeguraYExtremadamenteLargaParaAlkeWalletCyberNeon2026
jwt.expiration=86400000

# URL de otros servicios
app.services.account.url=https://account-service-1041045148793.us-central1.run.app

# --- RESILIENCE4J CONFIGURATION ---
resilience4j.circuitbreaker.instances.accountService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.accountService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.accountService.sliding-window-size=10
resilience4j.circuitbreaker.instances.accountService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.accountService.register-health-indicator=true


# --- ACTUATOR & PROBES ---
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.health.probes.enabled=true
management.endpoint.health.group.readiness.include=db
