spring.application.name=alkewallet
spring.main.allow-circular-references=true

# 1. PUERTO (Vital para Render)
server.port=${PORT:8080}

# 2. CONFIGURACIÓN DE BASE DE DATOS (PostgreSQL en Render)
# Reemplaza con tus credenciales reales de la pestaña 'External Database URL' o env vars
spring.datasource.url=${postgresql://kevin:km9HtfSgjFNm028TkbFBLx2mQBf8nexg@dpg-d7hec4ugvqtc738kqpc0-a.oregon-postgres.render.com/alkewallet_db_90fn}
spring.datasource.username=${kevin}
spring.datasource.password=${km9HtfSgjFNm028TkbFBLx2mQBf8nexg}
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. SEGURIDAD (Opcional, para debug)
logging.level.org.springframework.security=DEBUG