spring.application.name=auth-service

# URL actualizada con el prefijo //google/ para el correcto funcionamiento del SocketFactory en Cloud Run
spring.datasource.url=jdbc:postgresql://google/alkewallet_auth_db?cloudSqlInstance=verdant-doodad-385514:us-central1:alkewallet-postgres1&socketFactory=com.google.cloud.sql.postgres.SocketFactory

spring.datasource.username=postgres 
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
spring.main.allow-circular-references=true

jwt.secret=TuClaveSecretaSuperSeguraYExtremadamenteLargaParaAlkeWalletCyberNeon2026
jwt.expiration=86400000

app.services.account.url=https://account-service-1041045148793.us-central1.run.app