spring.application.name=account-service

# Conexión Directa a tu Base de Datos en Google Cloud
spring.datasource.url=jdbc:postgresql://8.35.197.211:5432/alkewallet_account_db
spring.datasource.username=postgres
spring.datasource.password=i%K3Ru4%24<_^]*?
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' para que cree la estructura de saldos y transacciones al levantar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Configuración de Pool de Conexiones (Hikari)
# ==========================================
# Máximo de conexiones simultáneas por instancia (ideal para entornos serverless)
spring.datasource.hikari.maximum-pool-size=3
# Permitir que las conexiones inactivas se cierren si no hay uso
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
# Puerto del servicio
server.port=${PORT:8082}
spring.main.allow-circular-references=true