spring.application.name=account-service

# --- CONFIGURACIÓN DE CONEXIÓN A CLOUD SQL ---
# Usamos ${VARIABLES} para que tome los valores de la consola de Cloud Run
spring.datasource.url=jdbc:postgresql://google/${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURACIÓN JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- SEGURIDAD (Obligatorio para evitar errores de arranque) ---
# Esto deshabilita la seguridad básica por defecto mientras terminas de configurar
spring.security.user.name=admin
spring.security.user.password=admin
management.endpoints.web.exposure.include=*

# --- PUERTO ---
server.port=${PORT:8080}