spring.application.name=account-service

# Conexión Segura mediante el Socket Interno (Cloud SQL Auth Proxy)
spring.datasource.url=jdbc:postgresql:///alkewallet_account_db?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=verdant-doodad-385514:us-east1:alkewallet-postgres1
spring.datasource.username=postgres
spring.datasource.password=i%K3Ru4%24<_^]*?
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de Pool de Conexiones (Hikari) optimizado
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Puerto del servicio dinámico
server.port=${PORT:8082}
spring.main.allow-circular-references=true