# Nombre de la aplicación
spring.application.name=auth-service


# --- CONFIGURACIÓN DE BASE DE DATOS ---
spring.datasource.url=jdbc:postgresql:///alkewallet_auth_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración del starter de Google Cloud SQL
# Esto crea el túnel de seguridad automáticamente
spring.cloud.gcp.sql.instance-connection-name=verdant-doodad-385514:us-central1:alkewallet-postgres1
spring.cloud.gcp.sql.database-name=alkewallet_auth_db

# --- CONFIGURACIÓN DE HIBERNATE / JPA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURACIÓN DEL SERVIDOR ---
server.port=${PORT:8080}
spring.main.allow-circular-references=true

# --- SEGURIDAD Y CONFIGURACIONES APP ---
jwt.secret=TuClaveSecretaSuperSeguraYExtremadamenteLargaParaAlkeWalletCyberNeon2026
jwt.expiration=86400000

# URL de otros servicios
app.services.account.url=https://account-service-1041045148793.us-central1.run.app