# Conexión a Render (PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d7hec4ugvqtc738kqpc0-a.oregon-postgres.render.com:5432/alkewallet_db_90fn
spring.datasource.username=kevin
spring.datasource.password=km9HtfSgjFNm028TkbFBLx2mQBf8nexg
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true